import 'package:flutter/material.dart';
import '../../core/calc_page.dart';
import '../../core/fmt.dart';
import '../../core/tool.dart';
import '../pdf/single_pdf_tool.dart' show Opt;
import '../text/text_tool_page.dart';
import 'more_logic.dart';

Tool _kc(String id, String ar, String en, String cat, IconData icon, List<String> kw,
        List<CalcField> fields, Rows? Function(List<String>) fn, {String? note}) =>
    Tool(
      id: id,
      nameAr: ar,
      nameEn: en,
      category: cat,
      keywords: kw,
      icon: icon,
      builder: (_) => CalcPage(title: ar, fields: fields, compute: fn, note: note),
    );

Tool _kt(String id, String ar, String en, String cat, IconData icon, List<String> kw, String hint,
        String Function(String, Map<String, String>) run,
        {List<Opt> options = const [], String? note}) =>
    Tool(
      id: id,
      nameAr: ar,
      nameEn: en,
      category: cat,
      keywords: kw,
      icon: icon,
      builder: (_) => TextToolPage(title: ar, hint: hint, run: run, options: options, note: note),
    );

const _blank = 'اترك الحقل فارغًا ليُحسب';

List<Tool> _geometry() => [
      _kc('geo_rect', 'مساحة ومحيط المستطيل', 'Rectangle', 'geo', Icons.rectangle_outlined,
          ['مستطيل', 'مساحة', 'محيط', 'قطر', 'rectangle', 'area', 'perimeter'],
          const [CalcField('الطول'), CalcField('العرض')], geoRect),
      _kc('geo_square', 'مساحة ومحيط المربع', 'Square', 'geo', Icons.crop_square,
          ['مربع', 'مساحة', 'محيط', 'square', 'area'], const [CalcField('طول الضلع')], geoSquare),
      _kc('geo_triangle', 'المثلث (بالأضلاع الثلاثة)', 'Triangle', 'geo', Icons.change_history,
          ['مثلث', 'مساحة', 'محيط', 'هيرون', 'triangle', 'area', 'heron'],
          const [CalcField('الضلع الأول'), CalcField('الضلع الثاني'), CalcField('الضلع الثالث')],
          geoTriangleSides),
      _kc('geo_triangle_bh', 'مساحة المثلث (قاعدة وارتفاع)', 'Triangle Area', 'geo', Icons.change_history,
          ['مثلث', 'مساحة', 'قاعدة', 'ارتفاع', 'triangle', 'area', 'base', 'height'],
          const [CalcField('القاعدة'), CalcField('الارتفاع')], geoTriangleBH),
      _kc('geo_circle', 'الدائرة', 'Circle', 'geo', Icons.circle_outlined,
          ['دائرة', 'مساحة', 'محيط', 'نصف القطر', 'قطر', 'circle', 'radius', 'pi'],
          const [CalcField('نصف القطر')], geoCircle),
      _kc('geo_trapezoid', 'مساحة شبه المنحرف', 'Trapezoid', 'geo', Icons.architecture,
          ['شبه منحرف', 'مساحة', 'trapezoid', 'area'],
          const [CalcField('القاعدة الأولى'), CalcField('القاعدة الثانية'), CalcField('الارتفاع')],
          geoTrapezoid),
      _kc('geo_parallelogram', 'متوازي الأضلاع', 'Parallelogram', 'geo', Icons.architecture,
          ['متوازي أضلاع', 'مساحة', 'محيط', 'parallelogram', 'area'],
          const [CalcField('القاعدة'), CalcField('الارتفاع'), CalcField('الضلع الجانبي')],
          geoParallelogram),
      _kc('geo_cube', 'حجم المكعب', 'Cube', 'geo', Icons.view_in_ar,
          ['مكعب', 'حجم', 'مساحة سطحية', 'cube', 'volume'], const [CalcField('طول الضلع')], geoCube),
      _kc('geo_cuboid', 'حجم متوازي المستطيلات', 'Cuboid', 'geo', Icons.view_in_ar,
          ['متوازي مستطيلات', 'حجم', 'صندوق', 'cuboid', 'box', 'volume'],
          const [CalcField('الطول'), CalcField('العرض'), CalcField('الارتفاع')], geoCuboid),
      _kc('geo_cylinder', 'الأسطوانة', 'Cylinder', 'geo', Icons.category_outlined,
          ['أسطوانة', 'اسطوانة', 'حجم', 'مساحة سطحية', 'خزان', 'cylinder', 'volume'],
          const [CalcField('نصف القطر'), CalcField('الارتفاع')], geoCylinder),
      _kc('geo_cone', 'المخروط', 'Cone', 'geo', Icons.category_outlined,
          ['مخروط', 'حجم', 'مساحة سطحية', 'cone', 'volume'],
          const [CalcField('نصف القطر'), CalcField('الارتفاع')], geoCone),
      _kc('geo_sphere', 'الكرة', 'Sphere', 'geo', Icons.public,
          ['كرة', 'حجم', 'مساحة سطحية', 'sphere', 'ball', 'volume'], const [CalcField('نصف القطر')], geoSphere),
      _kc('geo_pythagoras', 'نظرية فيثاغورس', 'Pythagoras', 'geo', Icons.square_foot,
          ['فيثاغورس', 'وتر', 'مثلث قائم', 'pythagoras', 'hypotenuse'],
          const [CalcField('الضلع الأول (أ)'), CalcField('الضلع الثاني (ب)'), CalcField('الوتر (ج)')],
          pythagoras, note: _blank),
      _kc('geo_right_triangle', 'الزوايا والأضلاع (مثلث قائم)', 'Right Triangle', 'geo', Icons.square_foot,
          ['زاوية', 'sin', 'cos', 'tan', 'جيب', 'جتا', 'ظل', 'مثلث قائم', 'angle', 'trigonometry'],
          const [
            CalcField('الضلع المقابل للزاوية'),
            CalcField('الضلع المجاور للزاوية'),
            CalcField('الوتر'),
            CalcField('الزاوية بالدرجات (بين 0 و90)'),
          ],
          rightTriangle,
          note: 'أدخل قيمتين فقط (ضلع واحد على الأقل) واترك الباقي فارغًا.'),
    ];

List<Tool> _science() => [
      _kc('sci_speed', 'السرعة والمسافة والزمن', 'Speed Distance Time', 'science', Icons.speed,
          ['سرعة', 'مسافة', 'زمن', 'فيزياء', 'speed', 'distance', 'time', 'physics'],
          const [CalcField('السرعة'), CalcField('المسافة'), CalcField('الزمن')],
          (v) => solveTriple(v, mul: false, labels: const ['السرعة', 'المسافة', 'الزمن']),
          note: '$_blank. استخدم وحدات متسقة (مثل كم، ساعة، كم/ساعة).'),
      _kc('sci_force', 'القوة (نيوتن)', 'Force', 'science', Icons.bolt,
          ['قوة', 'كتلة', 'تسارع', 'نيوتن', 'فيزياء', 'force', 'mass', 'acceleration', 'newton'],
          const [CalcField('القوة (نيوتن)'), CalcField('الكتلة (كجم)'), CalcField('التسارع (م/ث²)')],
          (v) => solveTriple(v, mul: true, labels: const ['القوة', 'الكتلة', 'التسارع']), note: _blank),
      _kc('sci_energy', 'الطاقة الحركية وطاقة الوضع', 'Energy', 'science', Icons.bolt,
          ['طاقة', 'حركية', 'وضع', 'جول', 'فيزياء', 'energy', 'kinetic', 'potential'],
          const [CalcField('الكتلة (كجم)'), CalcField('السرعة (م/ث)'), CalcField('الارتفاع (م)')],
          energyRows, note: 'اترك السرعة أو الارتفاع فارغًا إن لم يلزم. الجاذبية 9.80665 م/ث².'),
      _kc('sci_power', 'القدرة (واط)', 'Power', 'science', Icons.electric_bolt,
          ['قدرة', 'شغل', 'واط', 'فيزياء', 'power', 'work', 'watt'],
          const [CalcField('القدرة (واط)'), CalcField('الشغل (جول)'), CalcField('الزمن (ث)')],
          (v) => solveTriple(v, mul: false, labels: const ['القدرة', 'الشغل', 'الزمن']), note: _blank),
      _kc('sci_pressure', 'الضغط (قوة ÷ مساحة)', 'Pressure', 'science', Icons.compress,
          ['ضغط', 'قوة', 'مساحة', 'باسكال', 'فيزياء', 'pressure', 'pascal'],
          const [CalcField('الضغط (باسكال)'), CalcField('القوة (نيوتن)'), CalcField('المساحة (م²)')],
          (v) => solveTriple(v, mul: false, labels: const ['الضغط', 'القوة', 'المساحة']), note: _blank),
      _kc('sci_density', 'الكثافة', 'Density', 'science', Icons.scale_outlined,
          ['كثافة', 'كتلة', 'حجم', 'فيزياء', 'density', 'mass', 'volume'],
          const [CalcField('الكثافة (كجم/م³)'), CalcField('الكتلة (كجم)'), CalcField('الحجم (م³)')],
          (v) => solveTriple(v, mul: false, labels: const ['الكثافة', 'الكتلة', 'الحجم']), note: _blank),
      _kc('sci_ohm', 'قانون أوم', 'Ohm\'s Law', 'science', Icons.electric_bolt,
          ['اوم', 'أوم', 'جهد', 'تيار', 'مقاومة', 'فولت', 'أمبير', 'كهرباء', 'ohm', 'voltage', 'current', 'resistance'],
          const [CalcField('الجهد (فولت)'), CalcField('التيار (أمبير)'), CalcField('المقاومة (أوم)')],
          (v) => solveTriple(v, mul: true, labels: const ['الجهد', 'التيار', 'المقاومة']), note: _blank),
      _kt('sci_stats', 'الإحصاء: المتوسط والوسيط والانحراف', 'Statistics', 'science', Icons.bar_chart,
          ['إحصاء', 'متوسط', 'وسيط', 'منوال', 'مدى', 'تباين', 'انحراف معياري', 'statistics', 'mean', 'median', 'mode', 'variance', 'deviation'],
          'اكتب الأرقام يفصل بينها مسافة أو فاصلة أو سطر جديد...', (s, o) => statsText(s)),
      _kc('sci_probability', 'الاحتمال الأساسي', 'Probability', 'science', Icons.casino_outlined,
          ['احتمال', 'احتمالات', 'فرصة', 'probability', 'chance', 'odds'],
          const [CalcField('عدد الحالات المرغوبة'), CalcField('عدد الحالات الكلي')], probabilityRows),
      _kc('sci_combinatorics', 'التباديل والتوافيق', 'Permutations & Combinations', 'science', Icons.functions,
          ['تباديل', 'توافيق', 'عاملي', 'factorial', 'permutation', 'combination', 'ncr', 'npr'],
          const [CalcField('n (العدد الكلي، حتى 500)'), CalcField('r (المختار)')], combinatoricsRows),
    ];

List<Tool> _finance() => [
      _kt('fin_unit_price', 'مقارنة الأسعار وسعر الوحدة', 'Unit Price', 'calc', Icons.price_check,
          ['سعر الوحدة', 'مقارنة', 'اسعار', 'أرخص', 'عبوة', 'عرض', 'unit price', 'compare', 'cheaper'],
          'اكتب في كل سطر: الكمية ثم السعر\nمثال:\n12 18\n20 27', (s, o) => unitPriceText(s)),
      _kc('fin_successive', 'الخصم المتتابع', 'Successive Discount', 'calc', Icons.local_offer_outlined,
          ['خصم', 'خصم متتابع', 'تخفيض', 'عرض', 'discount', 'successive'],
          const [
            CalcField('السعر الأصلي'),
            CalcField('الخصم الأول %'),
            CalcField('الخصم الثاني % (اختياري)'),
            CalcField('الخصم الثالث % (اختياري)'),
          ],
          successiveDiscount),
      _kc('fin_final_price', 'السعر النهائي بعد الخصم والضريبة', 'Final Price', 'calc', Icons.percent,
          ['خصم', 'ضريبة', 'سعر نهائي', 'قيمة مضافة', 'final price', 'tax', 'discount', 'vat'],
          const [
            CalcField('السعر'),
            CalcField('الخصم %', initial: '0'),
            CalcField('الضريبة %', initial: '15'),
          ],
          finalPrice,
          note: 'تُحسب الضريبة على السعر بعد الخصم. عدّل نسبة الضريبة حسب بلدك.'),
      _kc('fin_salary', 'حاسبة الراتب', 'Salary', 'calc', Icons.payments_outlined,
          ['راتب', 'صافي', 'بدلات', 'استقطاع', 'تأمينات', 'salary', 'net', 'allowance'],
          const [
            CalcField('الراتب الأساسي'),
            CalcField('بدل السكن'),
            CalcField('بدل النقل'),
            CalcField('بدلات أخرى'),
            CalcField('نسبة الاستقطاع % (على الأساسي والسكن)'),
            CalcField('استقطاعات أخرى (مبلغ)'),
          ],
          salaryRows,
          note: 'نسبة الاستقطاع (مثل التأمينات) تختلف حسب نظامك، فأدخلها بنفسك. الحقول الفارغة تُحسب صفرًا.'),
    ];

List<Tool> _car() => [
      _kc('car_economy', 'استهلاك الوقود (كم/لتر)', 'Fuel Economy', 'car', Icons.local_gas_station_outlined,
          ['استهلاك', 'بنزين', 'وقود', 'سيارة', 'لتر', 'fuel economy', 'consumption', 'mpg'],
          const [CalcField('المسافة المقطوعة (كم)'), CalcField('كمية الوقود المستهلكة (لتر)')], fuelEconomy),
      _kt('car_units', 'تحويل وحدات استهلاك الوقود', 'Fuel Units', 'car', Icons.swap_horiz,
          ['استهلاك', 'وقود', 'سيارة', 'ميل', 'غالون', 'mpg', 'fuel', 'l/100km'],
          'اكتب القيمة (مثال: 8.5)', (s, o) => fuelUnitsText(s, o['from'] ?? 'l100'),
          options: const [
            Opt.choice('from', 'القيمة المُدخلة بوحدة',
                [('l100', 'لتر / 100 كم'), ('kmpl', 'كم / لتر'), ('mpgus', 'ميل / غالون (أمريكي)'), ('mpguk', 'ميل / غالون (بريطاني)')],
                initial: 'l100'),
          ]),
      _kc('car_trip_time', 'مدة الرحلة', 'Trip Duration', 'car', Icons.route,
          ['رحلة', 'مدة', 'سفر', 'وقت', 'سيارة', 'مسافة', 'سرعة', 'trip', 'duration', 'travel time'],
          const [CalcField('المسافة (كم)'), CalcField('متوسط السرعة (كم/ساعة)'), CalcField('استراحات (دقيقة)')],
          tripDuration,
          note: 'استراحات اختيارية. المدة تقديرية ولا تشمل الزحام.'),
      _kc('car_trip_split', 'تكلفة الرحلة وتقسيمها', 'Trip Cost Split', 'car', Icons.groups_outlined,
          ['رحلة', 'تقسيم', 'تكلفة', 'سفر', 'بنزين', 'اشخاص', 'سيارة', 'trip', 'split', 'cost'],
          const [
            CalcField('المسافة (كم)'),
            CalcField('الاستهلاك (لتر لكل 100 كم)'),
            CalcField('سعر اللتر'),
            CalcField('رسوم أخرى (طريق، مواقف...)'),
            CalcField('عدد الأشخاص', initial: '1'),
          ],
          tripSplit),
    ];

List<Tool> _home() => [
      _kc('home_room', 'مساحة وحجم الغرفة', 'Room Area', 'home', Icons.home_outlined,
          ['غرفة', 'مساحة', 'حجم', 'جدران', 'منزل', 'room', 'area', 'volume'],
          const [CalcField('الطول (م)'), CalcField('العرض (م)'), CalcField('الارتفاع (م) اختياري')],
          roomAreaRows),
      _kc('home_tiles', 'كمية البلاط', 'Tiles', 'home', Icons.grid_view,
          ['بلاط', 'سيراميك', 'هدر', 'كرتون', 'ارضية', 'منزل', 'tiles', 'floor', 'ceramic'],
          const [
            CalcField('طول الغرفة (م)'),
            CalcField('عرض الغرفة (م)'),
            CalcField('طول البلاطة (سم)'),
            CalcField('عرض البلاطة (سم)'),
            CalcField('نسبة الهدر %', initial: '10'),
            CalcField('عدد البلاط في الكرتون (اختياري)'),
          ],
          tilesRows),
      _kc('home_paint', 'كمية الدهان', 'Paint', 'home', Icons.format_paint_outlined,
          ['دهان', 'طلاء', 'جدران', 'لتر', 'منزل', 'paint', 'walls'],
          const [
            CalcField('طول الغرفة (م)'),
            CalcField('عرض الغرفة (م)'),
            CalcField('ارتفاع الجدار (م)'),
            CalcField('مساحة الأبواب والنوافذ (م²)', initial: '0'),
            CalcField('عدد الطبقات', initial: '2'),
            CalcField('تغطية اللتر (م²)', initial: '10'),
          ],
          paintRows,
          note: 'تغطية اللتر تختلف حسب نوع الدهان (راجع العبوة).'),
      _kc('home_tank_rect', 'سعة خزان مستطيل', 'Rectangular Tank', 'home', Icons.water_drop_outlined,
          ['خزان', 'سعة', 'ماء', 'حجم', 'لتر', 'منزل', 'tank', 'capacity', 'water'],
          const [CalcField('الطول (م)'), CalcField('العرض (م)'), CalcField('الارتفاع (م)')], tankRect),
      _kc('home_tank_cyl', 'سعة خزان أسطواني', 'Cylindrical Tank', 'home', Icons.water_drop_outlined,
          ['خزان', 'سعة', 'ماء', 'حجم', 'لتر', 'اسطواني', 'منزل', 'tank', 'cylinder', 'water'],
          const [CalcField('القطر (م)'), CalcField('الارتفاع (م)')], tankCylinder),
    ];

List<Tool> _timeAndText() => [
      _kc('time_add_dates', 'إضافة أو طرح مدة من تاريخ', 'Add to Date', 'time', Icons.event_outlined,
          ['تاريخ', 'اضافة', 'طرح', 'ايام', 'اسابيع', 'شهر', 'موعد', 'بعد', 'add days', 'date', 'subtract'],
          const [
            CalcField('التاريخ (سنة-شهر-يوم)', text: true),
            CalcField('أيام'),
            CalcField('شهور'),
            CalcField('سنوات'),
          ],
          addDatesRows,
          note: 'مثال التاريخ: 2026-10-05. للطرح اكتب رقمًا سالبًا (مثل -30). الحقول الفارغة تعني صفرًا.'),
      _kc('time_weekday', 'يوم الأسبوع لأي تاريخ', 'Weekday', 'time', Icons.today,
          ['يوم', 'اسبوع', 'تاريخ', 'سنة كبيسة', 'weekday', 'week number', 'leap'],
          const [CalcField('التاريخ (سنة-شهر-يوم)', text: true)], weekdayRows),
      _kc('time_work_hours', 'حاسبة ساعات العمل', 'Work Hours', 'time', Icons.work_outline,
          ['ساعات العمل', 'دوام', 'اجر', 'اجر بالساعة', 'استراحة', 'work hours', 'shift', 'timesheet'],
          const [
            CalcField('بداية الدوام (مثل 08:30)', text: true),
            CalcField('نهاية الدوام (مثل 17:00)', text: true),
            CalcField('استراحة (دقيقة)'),
            CalcField('الأجر بالساعة (اختياري)'),
            CalcField('عدد الأيام', initial: '1'),
          ],
          workHoursRows,
          note: 'إذا كانت النهاية أصغر من البداية يُحسب دوام ليلي يمتد لليوم التالي.'),
      _kc('time_add_time', 'جمع وطرح الأوقات', 'Add Times', 'time', Icons.access_time,
          ['جمع', 'طرح', 'وقت', 'ساعات', 'دقائق', 'add time', 'subtract time', 'hours', 'minutes'],
          const [
            CalcField('الوقت الأول (ساعة:دقيقة:ثانية)', text: true),
            CalcField('الوقت الثاني', text: true),
          ],
          addTimeRows,
          note: 'أمثلة: 01:30 أو 12:45:20 (الساعات قد تتجاوز 24).'),
      _kt('text_json', 'منسّق JSON ومدقّقه', 'JSON Formatter', 'text', Icons.data_object,
          ['json', 'جيسون', 'تنسيق', 'تحقق', 'ضغط', 'minify', 'validate', 'format', 'beautify'],
          'الصق نص JSON هنا...', (s, o) => jsonTool(s, o['mode'] ?? 'format'),
          options: const [
            Opt.choice('mode', 'العملية',
                [('format', 'تنسيق'), ('minify', 'ضغط'), ('validate', 'تحقق فقط')],
                initial: 'format'),
          ]),
      _kt('text_base64', 'ترميز Base64', 'Base64', 'text', Icons.lock_outline,
          ['base64', 'ترميز', 'فك', 'encode', 'decode'], 'اكتب النص هنا...',
          (s, o) => base64Tool(s, decode: o['mode'] == 'decode', urlSafe: o['safe'] == 'true'),
          options: const [
            Opt.choice('mode', 'العملية', [('encode', 'ترميز'), ('decode', 'فك الترميز')], initial: 'encode'),
            Opt.toggle('safe', 'صيغة آمنة للروابط (URL-safe)'),
          ]),
      _kt('text_url', 'ترميز الروابط (URL)', 'URL Encode', 'text', Icons.link,
          ['url', 'رابط', 'ترميز', 'encode', 'decode', 'percent'], 'اكتب النص أو الرابط هنا...',
          (s, o) => urlTool(s, decode: o['mode'] == 'decode', full: o['full'] == 'true'),
          options: const [
            Opt.choice('mode', 'العملية', [('encode', 'ترميز'), ('decode', 'فك الترميز')], initial: 'encode'),
            Opt.toggle('full', 'رابط كامل (لا يرمّز : و / و ؟ و &)'),
          ]),
    ];

final List<Tool> moreTools = [
  ..._geometry(),
  ..._science(),
  ..._finance(),
  ..._car(),
  ..._home(),
  ..._timeAndText(),
];
